### ISSUE TITLE
How to Get the Symbolic Expression from the Model?

### ISSUE THREAD

**Issue by augustocsc** [Hengzhe-Zhang/PS-Tree#3]
I've read the code to find a simple way to get the symbolic expression from the trained model but couldn't find any. 

How can I do that?

**Comment by hengzhe-zhang** [comment]
Thanks for your interest in this package.  Just using `e.model()`  is able to get a string of the final model.

**Comment by augustocsc** [comment]
wow 
huge result string here... I'll investigate how to improve to a "simpler" result, thanks!
