### ISSUE TITLE
请问如何显式的看到决策树和分段拟合结果？

### ISSUE THREAD

**Issue by Blackflappybird** [Hengzhe-Zhang/PS-Tree#4]
请问如何显式的看到决策树和分段拟合结果？

**Comment by Blackflappybird** [comment]
不是计算机专业，属于传统行业，看到论文转过来的，试了一些简单输入输出。
看到了issue2中的e.model()， 但不太清楚什么是e。

**Comment by Blackflappybird** [comment]
代码为示例给出的代码
`import deap
import pstree
import pyximport
from pstree.cluster_gp_sklearn import PSTreeRegressor, GPRegressor
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split

from numpy.testing import assert_almost_equal
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeRegressor

from matplotlib import pyplot as plt
import numpy as np

X = 2 * np.random.randn(300, 5)
y = 2.5382 * np.cos(X[:, 3]) + X[:, 0] ** 2 - 0.5 + np.sin(X[:, 4])+X[:, 1] ** 3

# X, y = load_diabetes(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
r = PSTreeRegressor(regr_class=GPRegressor, tree_class=DecisionTreeRegressor,
                    height_limit=6, n_pop=25, n_gen=100,
                    basic_primitive='optimal', size_objective=True)
r.fit(x_train, y_train)
print(r2_score(y_test, r.predict(x_test)))

plt.plot(y_test)
plt.plot(r.predict(x_test))

plt.show()`

r.model()提示：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [37], in <cell line: 1>()
----> 1 r.model()

AttributeError: 'PSTreeRegressor' object has no attribute 'model'

**Comment by hengzhe-zhang** [comment]
感谢对遗传编程的关注，PS-Tree在PIP仓库中的代码还没有来得及更新，目前可以考虑直接使用GitHub提供的代码。

**Comment by Blackflappybird** [comment]
谢谢~
