### ISSUE TITLE
problems during package installation

### ISSUE THREAD

**Issue by andereles** [Hengzhe-Zhang/PS-Tree#6]
* PSTree version: v0.1.1
* Python version: 3.10.4
* Operating System: Windows 11

### Description
I'm trying to pip install the PS-Tree and a error occurs during the package installation.

### What I Did

!pip install -U pstree
_________________________
Collecting pstree
  Downloading pstree-0.1.1-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pstree) (1.22.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pstree) (1.5.3)
Collecting gplearn (from pstree)
  Downloading gplearn-0.4.2-py3-none-any.whl (25 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from pstree) (1.10.1)
Collecting deap (from pstree)
  Downloading deap-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.4/135.4 kB 5.4 MB/s eta 0:00:00
Collecting bluepyopt (from pstree)
  Downloading bluepyopt-1.14.0-py3-none-any.whl (217 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.4/217.4 kB 10.2 MB/s eta 0:00:00
Collecting glmnet (from pstree)
  Downloading glmnet-2.2.1.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 kB 7.1 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hengzhe-zhang** [comment]
Thanks. I believe this problem is caused by glmnet and Windows. Please install pstree in a Linux environment. Alternatively, raise an issue with the maintainer of glmnet.

I can easily install pstree with the following commands:

```python
conda create --name pstree python=3.8
conda activate pstree
pip install pstree -U
```

**Comment by andereles** [comment]
Thanks! I'll reach the glmnet maintainer.
