### ISSUE TITLE
ImportError: cannot import name 'Ephemeral' from 'deap.gp'

### ISSUE THREAD

**Issue by IronTessaro** [Hengzhe-Zhang/PS-Tree#7]
* PSTree version: 0.1.0
* Python version: 3.10.12
* Operating System: (Jupyter notebook)

### Description

ImportError: cannot import name 'Ephemeral' from 'deap.gp'

### What I Did

While trying to import PSTreeRegressor: 
from pstree.cluster_gp_sklearn import PSTreeRegressor, GPRegressor

Got the error: ImportError: cannot import name 'Ephemeral' from 'deap.gp'. It seems the class changed from Ephemeral to MetaEphemeral in deap module

---> 12 from pstree.cluster_gp_sklearn import PSTreeRegressor, GPRegressor
     13 
     14 X, y = load_diabetes(return_X_y=True)

[/usr/local/lib/python3.10/dist-packages/pstree/cluster_gp_sklearn.py](https://localhost:8080/#) in <module>
      9 import numpy
     10 import pyximport
---> 11 from deap.gp import Terminal, Ephemeral
     12 from deap.tools import selNSGA2, selRandom, selSPEA2, selLexicase, selNSGA3
     13 from icecream import ic

ImportError: cannot import name 'Ephemeral' from 'deap.gp' (/usr/local/lib/python3.10/dist-packages/deap/gp.py)
```

**Comment by hengzhe-zhang** [comment]
In the latest version of DEAP, the author changed "Ephemeral" to "MetaEphemeral." Therefore, the simplest way is to install the old version of DEAP. I will attempt to address this issue in the near future.

**Comment by hengzhe-zhang** [comment]
I have uploaded the package to PyPI, which I believe will solve this issue. If you still encounter issues, please don't hesitate to reopen this issue ticket.
