### ISSUE TITLE
TypeError: _alpha_grid() got an unexpected keyword argument 'normalize'

### ISSUE THREAD

**Issue by Qiuling-Tao** [Hengzhe-Zhang/PS-Tree#8]
* PSTree version:0.1.1
* Python version:3.9.18
* Operating System:Ubuntu20.04.6 LTS

### Description
老师您好，我在Ubuntu中安装了pstree，但在尝试运行所给的例子的时候出现了错误，是否是某个包不兼容？
TypeError: _alpha_grid() got an unexpected keyword argument 'normalize'

### What I Did

from sklearn.datasets import load_diabetes
X, y = load_diabetes(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
r = PSTreeRegressor(regr_class=GPRegressor, tree_class=DecisionTreeRegressor,
                    height_limit=6, n_pop=25, n_gen=100,
                    basic_primitive='optimal', size_objective=True)
r.fit(x_train, y_train)
print(r2_score(y_test, r.predict(x_test)))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
e:/ubuntu/python/test.ipynb Cell 5 line 6
      2 x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
      3 r = PSTreeRegressor(regr_class=GPRegressor, tree_class=DecisionTreeRegressor,
      4                     height_limit=6, n_pop=25, n_gen=100,
      5                     basic_primitive='optimal', size_objective=True)
----> 6 r.fit(x_train, y_train)
      7 print(r2_score(y_test, r.predict(x_test)))

File ~/anaconda3/envs/pstree/lib/python3.9/site-packages/pstree/cluster_gp_sklearn.py:72, in train_normalization.<locals>.call(self, X, y, *param, **dict_param)
     70     X = self.x_scaler.fit_transform(X)
     71     y = self.y_scaler.fit_transform(y.reshape(-1, 1)).squeeze()
---> 72 result = func(self, X, y, *param, **dict_param)
     73 return result

File ~/anaconda3/envs/pstree/lib/python3.9/site-packages/pstree/cluster_gp_sklearn.py:969, in PSTreeRegressor.fit(self, X, y)
    963     self.tree_class = LogisticRegression
    965 self.regr: GPRegressor = self.regr_class(max_depth=self.max_depth, min_samples_leaf=self.min_samples_leaf,
    966                                          space_partition_fun=self.space_partition,
    967                                          basic_primitive=self.basic_primitive, soft_tree=self.soft_tree,
    968                                          adaptive_tree=self.adaptive_tree, super_object=self, **self.params)
--> 969 self.regr.fit(X, y, category)
    970 return self
...
    409     ridge_model = ElasticNet(alpha=1, lambda_path=alphas, n_splits=5, tol=1e-4,
    410                              random_state=0)
    411     return ridge_model

TypeError: _alpha_grid() got an unexpected keyword argument 'normalize'

**Comment by hengzhe-zhang** [comment]
Thank you for reporting this issue. The scikit-learn library has changed its API, causing an error to occur. I have uploaded a new version to PyPI to fix this issue. Please upgrade the `PS-Tree` package to resolve it. Thanks!

**Comment by Qiuling-Tao** [comment]
Thank you for your reply. The issue has been solved after updating the PS-Tree package
